package com.ita.if103java.ims.util;

import com.ita.if103java.ims.exception.dao.CRUDException;
import org.springframework.data.domain.Sort;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.util.NumberUtils;

import java.util.Optional;
import java.util.function.Consumer;
import java.util.stream.Collectors;

public class JDBCUtils {
    public static <T extends Number> T createWithAutogeneratedId(Class<T> idType, Consumer<KeyHolder> consumer, KeyHolder keyHolder) {
        consumer.accept(keyHolder);
        return Optional
            .ofNullable(keyHolder.getKey())
            .map(number -> NumberUtils.convertNumberToTargetClass(number, idType))
            .orElseThrow(() -> new CRUDException("Failed to generate PK"));
    }

    public static Long createWithAutogeneratedId(Consumer<KeyHolder> consumer, KeyHolder keyHolder) {
        return createWithAutogeneratedId(Long.class, consumer, keyHolder);
    }

    public static String getOrder(Sort sort) {
        return sort.stream()
            .map(x -> x.getProperty() + " " + x.getDirection().name())
            .collect(Collectors.joining(", "));
    }
}
